version: '3.8'

services:
  nestjs-metrics:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Replace with desired port mapping
    # other configurations if needed